stages:
  - verify
  - test
  - build

.vendor:
  - &vendor
    if [ ! -d "vendor" ]; then
      make setup:vendor;
    fi

.cache: &cache
  cache:
    key:
      files:
        - Cargo.lock
      # NOTE: set an environment variable `CI_CACHE_VERSION`
      prefix: "${CI_PROJECT_NAME}-cache-${CI_CACHE_VERSION}"
    paths:
      - .cargo
      - vendor

.vet-tools: &vet-tools
  image: grauwoelfchen/rust-vet-tools:1.40.0-stable
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
    - cargo clippy --version
    - kcov --version
    - *vendor
    - mkdir -p .git/hooks
  <<: *cache

.rust: &rust
  image: grauwoelfchen/rust:1.40.0-stable
  before_script:
    - rustc --version
    - cargo --version
    - cargo fmt --version
    - cargo clippy --version
    - *vendor
    - mkdir -p .git/hooks
  <<: *cache

# -- verify {{{
check:
  stage: verify
  <<: *rust
  script:
    - make verify:check

format:
  stage: verify
  <<: *rust
  script:
    - make verify:format

lint:
  stage: verify
  <<: *rust
  script:
    - make verify:lint
# }}}

# -- test {{{
test:
  stage: test
  <<: *vet-tools
  script:
    # test & get covered
    - KCOV_PATH=/usr/bin/kcov make coverage
  after_script:
    - cat target/coverage/index.json
  except:
    - tags
# }}}

# -- build {{{
build:
  stage: build
  <<: *rust
  script:
    - make build:debug
  only:
    - master

release:
  stage: build
  <<: *rust
  script:
    - make build:release
  only:
    - tags
# }}}
